version: '3.9'
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - 3000:3000

  scrape:
    build: 
      context: ./Scraper
      dockerfile: Dockerfile
    volumes:
      - ./Scraper:/scrape-app/Scraper
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1